version: '3.4'

services:
  main:
    build: ./
    command: python3 main.py
    restart: always

  main_tasks_keys:
    build: ./
    command: python3 main_tasks_keys.py
    restart: always

  main_tasks_source:
    build: ./
    command: python3 main_tasks_source.py
    restart: always
