version: '3.4'

services:
#  main:
#    build: ./
#    command: python3 main.py
#    restart: always
#    deploy:
#      resources:
#        limits:
#          memory: 150Mb
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#
#  main_tasks_keys:
#    build: ./
#    command: python3 main_tasks_keys.py
#    restart: always
#    deploy:
#      resources:
#        limits:
#          memory: 1GB
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#
#  main_tasks_source:
#    build: ./
#    command: python3 main_tasks_source.py
#    restart: always
#    deploy:
#      resources:
#        limits:
#          memory: 200Mb
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"

  main_script:
    build: ./
    command: python3 m_t.py
    restart: always
    deploy:
      resources:
        limits:
          memory: 200Mb
    logging:
      driver: "json-file"
      options:
        max-size: "100m"