# Generated by Django 3.1.4 on 2022-03-30 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=256)),
                ('port', models.IntegerField()),
                ('login', models.CharField(max_length=256)),
                ('proxy_password', models.CharField(max_length=256)),
                ('failed', models.IntegerField()),
                ('errors', models.IntegerField()),
                ('foregin', models.IntegerField()),
                ('banned_fb', models.IntegerField()),
                ('banned_y', models.IntegerField()),
                ('banned_tw', models.IntegerField()),
                ('timezone', models.CharField(max_length=256)),
                ('v6', models.IntegerField()),
                ('checking', models.BooleanField()),
            ],
            options={
                'db_table': 'prsr_parser_proxy',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('network_id', models.IntegerField(default=0)),
                ('keyword', models.CharField(default='nexta_live', max_length=4096)),
                ('enabled', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('depth', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('taken', models.BooleanField(default=0)),
                ('reindexing', models.BooleanField(default=0)),
                ('forced', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'prsr_parser_keywords',
            },
        ),
        migrations.CreateModel(
            name='KeywordSource',
            fields=[
                ('keyword_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_id', models.IntegerField()),
            ],
            options={
                'db_table': 'prsr_parser_source_keywords',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sphinx_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prsr_parser_ok_users',
            },
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'prsr_parser_ok_content',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('from_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('likes', models.IntegerField(default=0)),
                ('reposts', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('found_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('content_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'prsr_parser_ok_post',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taken', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('errors', models.IntegerField(default=0)),
                ('banned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'prsr_parser_proxy_ok',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('published', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=0)),
                ('type', models.CharField(default='profiles', max_length=4096)),
                ('retro', models.DateField(blank=True, null=True)),
                ('retro_max', models.DateField(blank=True, null=True)),
                ('networks', models.IntegerField(default=0)),
                ('taken', models.BooleanField(default=1)),
                ('linking', models.BooleanField(default=0)),
                ('sources', models.IntegerField(default=15)),
                ('profiles', models.IntegerField(default=15)),
                ('stats_params', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'prsr_parser_sources',
            },
        ),
        migrations.CreateModel(
            name='SourcesItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('network_id', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=1)),
                ('data', models.CharField(default='nexta_live', max_length=4096)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('taken', models.BooleanField(default=0)),
                ('reindexing', models.BooleanField(default=0)),
                ('disabled', models.BooleanField(default=0)),
                ('forced', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'prsr_parser_source_items',
            },
        ),
        migrations.CreateModel(
            name='UpdateIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('owner_id', models.IntegerField()),
                ('network_id', models.IntegerField(default=8)),
                ('sphinx_id', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'prsr_update_index',
            },
        ),
    ]
